-- documents.status ENUM에 ANALYZING, REJECTED 추가
ALTER TABLE documents MODIFY COLUMN status ENUM('UPLOADING','ANALYZING','PARSING','GENERATING','READY','REJECTED','FAILED') NOT NULL DEFAULT 'UPLOADING';

-- review_queue_items.status ENUM에 DEFERRED, CONFUSED 추가
ALTER TABLE review_queue_items MODIFY COLUMN status ENUM('PENDING','COMPLETED','DISMISSED','DEFERRED','CONFUSED') NOT NULL DEFAULT 'PENDING';
